In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('../Dataset/Accident/Accident 2014.csv')

In [7]:
df.head()

,Reference Number,Grid Ref: Easting,Grid Ref: Northing,Number of Vehicles,Accident Date,Time (24hr),1st Road Class,1st Road Class & No,Road Surface,Lighting Conditions,Weather Conditions,Local Authority,Casualty Class,Casualty Severity,Sex of Casualty,Age of Casualty,Vehicle Number,Type of Vehicle
0,11S0281,407491,428929,1,28/01/2014,835,6,U,2,1,9,Calderdale,3,3,2,8,1,9
1,11S1147,412912,429039,1,28/01/2014,1745,6,U,2,4,1,Calderdale,3,3,2,15,1,9
2,11S1147,412912,429039,1,28/01/2014,1745,6,U,2,4,1,Calderdale,3,3,1,17,1,9
3,11U0285,407179,424776,2,30/01/2014,900,6,U,2,1,8,Calderdale,1,3,2,29,2,9
4,11U0285,407179,424776,2,30/01/2014,900,6,U,2,1,8,Calderdale,2,3,1,9,2,9

In [14]:
column_names = df.columns.to_list()

In [15]:
type(column_names)

list

In [16]:
df[column_names[0]].nunique()

427

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 623 entries, 0 to 622
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Reference Number     623 non-null    str
 1   Grid Ref: Easting    623 non-null    int64
 2   Grid Ref: Northing   623 non-null    int64
 3   Number of Vehicles   623 non-null    int64
 4   Accident Date        623 non-null    str
 5   Time (24hr)          623 non-null    int64
 6   1st Road Class       623 non-null    int64
 7   1st Road Class & No  623 non-null    str
 8   Road Surface         623 non-null    int64
 9   Lighting Conditions  623 non-null    int64
 10  Weather Conditions   623 non-null    int64
 11  Local Authority      623 non-null    str
 12  Casualty Class       623 non-null    int64
 13  Casualty Severity    623 non-null    int64
 14  Sex of Casualty      623 non-null    int64
 15  Age of Casualty      623 non-null    int64
 16  Vehicle Number       623 non-null    int64
 17  Type of Vehicle      623 non-null    int64
dtypes: int64(14), str(4)
memory usage: 87.7 KB

In [27]:
df.drop_duplicates(inplace= True)
df.duplicated().sum()

np.int64(0)

In [29]:
pd.crosstab(df['Reference Number'],df['Grid Ref: Easting'])

Grid Ref: Easting,389828,390043,392729,392964,392993,393060,393120,393267,393325,393375,...,416481,416495,416512,416591,416610,416879,416893,416982,417061,417811
Reference Number,,,,,,,,,,,,,,,,,,,,,
1.90E+243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11S0281,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11S1147,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11U0285,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11U1201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1CQ1464,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1CT0204,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1CU0561,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1CU0803,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1CV0997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0