In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../Dataset/StudentsPerformance.csv")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [18]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,NaN,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,NaN,90,95,93
3,male,group A,associate's degree,free/reduced,NaN,47,57,44
4,male,group C,some college,standard,NaN,76,78,75

In [4]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [5]:
df.describe(include='str')

,gender,race/ethnicity,parental level of education,lunch,test preparation course
count,1000,1000,1000,1000,1000
unique,2,5,6,2,2
top,female,group C,some college,standard,none
freq,518,319,226,645,642

In [15]:
df['test preparation course'].unique()

<StringArray>
[nan, 'completed']
Length: 2, dtype: str

In [8]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [14]:
df["test preparation course"] = df["test preparation course"].replace({"none":np.nan})

In [17]:
df.isnull().sum()

gender                           0
race/ethnicity                   0
parental level of education      0
lunch                            0
test preparation course        642
math score                       0
reading score                    0
writing score                    0
dtype: int64

In [22]:
prep_comp = df[df["test preparation course"] == 'completed' ]
prep_comp.info()

<class 'pandas.DataFrame'>
Index: 358 entries, 1 to 998
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       358 non-null    str
 1   race/ethnicity               358 non-null    str
 2   parental level of education  358 non-null    str
 3   lunch                        358 non-null    str
 4   test preparation course      358 non-null    str
 5   math score                   358 non-null    int64
 6   reading score                358 non-null    int64
 7   writing score                358 non-null    int64
dtypes: int64(3), str(5)
memory usage: 25.2 KB

In [23]:
prep_comp.describe()

       math score  reading score  writing score
count  358.000000     358.000000     358.000000
mean    69.695531      73.893855      74.418994
std     14.444699      13.638384      13.375335
min     23.000000      37.000000      36.000000
25%     60.000000      65.000000      66.000000
50%     69.000000      75.000000      76.000000
75%     79.000000      84.000000      83.000000
max    100.000000     100.000000     100.000000