the column name farm_id contains only unique values
the column named sensor_id contains only unique values
These two columns doesnt contrinute anthing for finding a relation in the dataset

in column crop disease some has null values
looking for the circumstances that a crop can have disease ,
based on the data given the type of the crop doesnt show any influence in affecting its stage of the diesease

so lets look for the fertilizer applied to it , the lack of fertilizers or medicine to the crop had made the crop severe in disease, since no crop will be initially has a severe disease
so the crop had the disease to severe because of lack of nutrients and medicine, while others who got proper medicine and nutrients survided, 

in this case there is also a set that gone undocumented which is the crops which never had any disease to begin with we also need to find them

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Dataset/dataset_final.csv")
df.head()

,farm_id,region_x,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,timestamp,latitude,longitude,NDVI_index,crop_disease_status,date_join,region_maroc,et0,wind_speed_max,radiation_sum
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,2024-03-19,14.970941,82.997689,0.63,Mild,2024-03-19,Gharb (Kenitra),4.238751,15.629972,21.21
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,2024-04-21,16.613022,70.869009,0.58,NaN,2024-04-21,Souss-Massa (Agadir),4.825523,40.464382,26.15
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,2024-02-28,19.503156,79.068206,0.80,Mild,2024-02-28,Souss-Massa (Agadir),3.696556,18.864824,19.71
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,2024-05-14,31.071298,85.519998,0.44,NaN,2024-05-14,Saiss (Fes),4.771625,19.800000,23.20
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,2024-04-13,16.568540,81.691720,0.84,Severe,2024-04-13,Saiss (Fes),6.550368,31.079075,25.68

In [3]:
df.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,409.000000,409.000000,409.000000
mean,26.750140,6.523980,24.675740,181.685740,65.194460,7.03014,26.586980,119.496000,4032.92694,22.442473,80.392248,0.602060,4.503720,20.401949,21.207262
std,10.150053,0.585558,5.348899,72.293091,14.642849,1.69167,13.202429,16.798046,1174.43304,7.283492,5.910664,0.175402,1.647743,7.539521,5.949149
min,10.160000,5.510000,15.000000,50.170000,40.230000,4.01000,5.050000,90.000000,2023.56000,10.004243,70.020021,0.300000,1.070605,7.993297,1.140000
25%,17.890000,6.030000,20.295000,119.217500,51.865000,5.66750,14.945000,105.750000,2994.82000,16.263202,75.374713,0.447500,3.349063,15.391840,17.000000
50%,25.855000,6.530000,24.655000,191.545000,65.685000,6.99500,25.980000,119.000000,4071.69000,21.981743,80.650284,0.610000,4.260496,19.272614,22.300000
75%,36.022500,7.040000,29.090000,239.035000,77.995000,8.47000,38.005000,134.000000,5062.11000,28.528948,85.654629,0.750000,5.718628,24.130743,26.620000
max,44.980000,7.500000,34.840000,298.960000,90.000000,10.00000,49.940000,150.000000,5998.29000,34.981531,89.991901,0.900000,10.369526,50.432130,29.620000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   farm_id               500 non-null    str
 1   region_x              500 non-null    str
 2   crop_type             500 non-null    str
 3   soil_moisture_%       500 non-null    float64
 4   soil_pH               500 non-null    float64
 5   temperature_C         500 non-null    float64
 6   rainfall_mm           500 non-null    float64
 7   humidity_%            500 non-null    float64
 8   sunlight_hours        500 non-null    float64
 9   irrigation_type       350 non-null    str
 10  fertilizer_type       500 non-null    str
 11  pesticide_usage_ml    500 non-null    float64
 12  sowing_date           500 non-null    str
 13  harvest_date          500 non-null    str
 14  total_days            500 non-null    int64
 15  yield_kg_per_hectare  500 non-null    float64
 16  sensor_id             500 non-null    str
 17  timestamp             500 non-null    str
 18  latitude              500 non-null    float64
 19  longitude             500 non-null    float64
 20  NDVI_index            500 non-null    float64
 21  crop_disease_status   370 non-null    str
 22  date_join             500 non-null    str
 23  region_maroc          409 non-null    str
 24  et0                   409 non-null    float64
 25  wind_speed_max        409 non-null    float64
 26  radiation_sum         409 non-null    float64
dtypes: float64(14), int64(1), str(12)
memory usage: 105.6 KB

In [5]:
df.duplicated(subset='farm_id').sum()

np.int64(0)

In [6]:
df['irrigation_type'].unique()

<StringArray>
[nan, 'Sprinkler', 'Drip', 'Manual']
Length: 4, dtype: str

In [7]:
df["irrigation_type"].isnull().sum()

np.int64(150)

In [8]:
df["crop_disease_status"].unique()

<StringArray>
['Mild', nan, 'Severe', 'Moderate']
Length: 4, dtype: str

In [9]:
df["crop_disease_status"].value_counts().sum()

np.int64(370)

In [10]:
df.duplicated(subset='sensor_id').sum()

np.int64(0)

In [11]:
df.columns

Index(['farm_id', 'region_x', 'crop_type', 'soil_moisture_%', 'soil_pH',
       'temperature_C', 'rainfall_mm', 'humidity_%', 'sunlight_hours',
       'irrigation_type', 'fertilizer_type', 'pesticide_usage_ml',
       'sowing_date', 'harvest_date', 'total_days', 'yield_kg_per_hectare',
       'sensor_id', 'timestamp', 'latitude', 'longitude', 'NDVI_index',
       'crop_disease_status', 'date_join', 'region_maroc', 'et0',
       'wind_speed_max', 'radiation_sum'],
      dtype='str')

In [12]:
mild_crops = df[df['crop_disease_status'] == 'Mild']
severe_crops = df[df['crop_disease_status'] == 'Severe']
moderate_crops = df[df['crop_disease_status'] == 'Moderate']

In [13]:
mild_crops.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,125.000000,104.000000,104.000000,104.000000
mean,26.454240,6.522480,24.645120,188.920000,66.027120,7.108640,26.859840,118.056000,4089.871760,22.455444,79.959087,0.614880,4.691548,20.979586,21.987788
std,10.248553,0.589433,5.343632,76.194344,14.762927,1.673326,13.170835,16.973558,1216.375522,7.043945,5.694626,0.173919,1.608153,7.279408,5.955354
min,10.340000,5.510000,15.040000,52.350000,40.640000,4.020000,5.420000,90.000000,2023.560000,10.130335,70.328707,0.300000,1.070605,8.496305,1.140000
25%,17.740000,5.990000,20.400000,119.430000,53.030000,5.820000,15.360000,103.000000,2969.170000,16.728993,74.493947,0.440000,3.594151,16.445138,18.085000
50%,25.810000,6.550000,24.480000,206.330000,68.870000,7.210000,26.790000,118.000000,4127.730000,21.383615,80.252939,0.650000,4.470083,19.741437,23.635000
75%,35.650000,7.040000,29.530000,250.510000,77.590000,8.410000,38.460000,133.000000,5264.090000,28.397232,84.356904,0.740000,6.077152,23.682096,27.270000
max,44.980000,7.500000,34.520000,298.960000,90.000000,10.000000,49.930000,148.000000,5980.830000,34.981531,89.974564,0.890000,7.958767,49.635630,29.350000

In [14]:
severe_crops.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,108.000000,108.000000,108.000000
mean,27.717218,6.564662,24.769774,184.842707,64.854812,7.131353,26.680075,118.082707,4029.344286,22.620897,80.784547,0.599624,4.405490,20.939993,20.943426
std,10.086458,0.548856,5.778950,69.764717,14.806035,1.642854,13.426515,16.546100,1210.496191,7.046603,5.591087,0.189710,1.698967,7.524606,6.177351
min,10.160000,5.510000,15.000000,50.170000,40.290000,4.020000,5.050000,90.000000,2043.130000,10.129536,70.353408,0.300000,1.268999,8.049845,3.580000
25%,18.750000,6.180000,19.850000,131.250000,51.280000,5.810000,13.530000,104.000000,3010.730000,16.566926,75.647282,0.440000,3.243150,15.922602,16.352500
50%,28.190000,6.610000,24.780000,193.920000,64.680000,6.960000,25.720000,115.000000,4131.770000,22.126535,80.768336,0.580000,4.351509,19.675153,22.095000
75%,36.260000,7.010000,29.200000,238.080000,78.410000,8.470000,39.610000,132.000000,4985.170000,28.219985,85.652925,0.770000,5.657759,23.756553,26.302500
max,44.690000,7.480000,34.710000,298.080000,89.740000,9.980000,49.910000,150.000000,5998.290000,34.899235,89.991901,0.900000,10.369526,50.432130,28.820000

In [15]:
severe_crops['crop_type'].unique()

<StringArray>
['Cotton', 'Rice', 'Maize', 'Soybean', 'Wheat']
Length: 5, dtype: str

In [16]:
cotton_s = severe_crops[severe_crops["crop_type"] == 'Cotton']
cotton_s.drop(columns=['crop_type','crop_disease_status'],inplace=True)
cotton_s

,farm_id,region_x,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,fertilizer_type,...,sensor_id,timestamp,latitude,longitude,NDVI_index,date_join,region_maroc,et0,wind_speed_max,radiation_sum
4,FARM0005,Central USA,19.37,5.92,33.86,269.09,55.73,7.93,NaN,Mixed,...,SENS0005,2024-04-13,16.568540,81.691720,0.84,2024-04-13,Saiss (Fes),6.550368,31.079075,25.68
24,FARM0025,South USA,18.54,6.81,15.11,237.74,78.50,4.64,NaN,Organic,...,SENS0025,2024-04-17,32.936750,72.427172,0.38,2024-04-17,Souss-Massa (Agadir),4.588980,19.855558,26.00
26,FARM0027,Central USA,12.71,6.07,20.43,129.93,67.01,4.83,Sprinkler,Inorganic,...,SENS0027,2024-04-18,23.565279,78.315485,0.42,2024-04-18,Saiss (Fes),5.100389,15.876775,24.45
28,FARM0029,Central USA,35.35,7.18,33.39,295.18,66.71,9.44,Drip,Organic,...,SENS0029,2024-03-01,19.477597,74.233206,0.50,2024-03-01,Saiss (Fes),2.605511,9.957108,16.37
32,FARM0033,South India,16.16,6.54,28.01,203.98,85.98,8.65,NaN,Inorganic,...,SENS0033,2024-06-23,33.365547,75.578565,0.57,2024-06-23,NaN,NaN,NaN,NaN
42,FARM0043,Central USA,38.47,6.60,24.10,128.63,56.16,9.82,NaN,Mixed,...,SENS0043,2024-05-06,11.355102,80.368788,0.67,2024-05-06,Saiss (Fes),4.324369,13.896187,21.25
44,FARM0045,South India,42.64,6.08,29.11,153.87,64.12,6.83,NaN,Mixed,...,SENS0045,2024-02-06,31.600673,75.524948,0.77,2024-02-06,NaN,NaN,NaN,NaN
46,FARM0047,East Africa,18.17,7.05,15.87,236.18,75.26,8.87,NaN,Mixed,...,SENS0047,2024-03-21,22.557279,81.803609,0.82,2024-03-21,Haouz (Marrakech),3.962534,20.172853,18.04
103,FARM0104,South USA,32.77,7.01,20.74,121.35,42.96,8.61,Sprinkler,Mixed,...,SENS0104,2024-01-28,33.348065,70.726797,0.80,2024-01-28,Souss-Massa (Agadir),6.508617,31.404713,15.81
108,FARM0109,East Africa,28.49,6.22,33.34,78.05,81.44,9.42,Sprinkler,Mixed,...,SENS0109,2024-02-09,27.007381,84.338359,0.59,2024-02-09,Haouz (Marrakech),1.637935,17.731598,3.58
122,FARM0123,North India,23.27,6.61,16.12,52.36,48.57,7.00,NaN,Mixed,...,SENS0123,2024-04-02,15.744162,88.025459,0.72,2024-04-02,Gharb (Kenitra),3.396973,14.118243,22.32
125,FARM0126,Central USA,27.17,6.21,33.82,157.96,73.98,7.96,Drip,Mixed,...,SENS0126,2024-02-11,19.500000,85.677806,0.39,2024-02-11,Saiss (Fes),2.287997,24.842607,11.99
131,FARM0132,East Africa,28.70,7.35,32.39,154.58,41.84,9.81,Drip,Organic,...,SENS0132,2024-06-08,11.107417,89.672164,0.71,2024-06-08,Haouz (Marrakech),5.648856,20.005120,24.39
135,FARM0136,East Africa,23.61,6.91,19.12,238.08,80.44,4.38,Drip,Mixed,...,SENS0136,2024-05-02,31.565914,80.554300,0.68,2024-05-02,Haouz (Marrakech),5.684468,19.734436,25.54
136,FARM0137,East Africa,30.55,6.20,31.91,204.34,80.69,8.24,Manual,Mixed,...,SENS0137,2024-04-13,12.923723,77.466121,0.38,2024-04-13,Haouz (Marrakech),7.539997,22.127556,26.87
139,FARM0140,East Africa,29.24,5.73,17.28,243.78,81.16,6.20,Drip,Mixed,...,SENS0140,2024-04-06,28.783637,75.954179,0.90,2024-04-06,Haouz (Marrakech),5.638671,24.162947,20.49
174,FARM0175,North India,16.05,7.47,34.44,252.12,46.31,6.54,NaN,Organic,...,SENS0175,2024-05-25,32.770112,88.283479,0.34,2024-05-25,Gharb (Kenitra),4.336485,15.137133,25.33
201,FARM0202,South India,38.86,5.88,21.76,239.29,42.33,7.80,Drip,Inorganic,...,SENS0202,2024-03-17,23.259109,70.971432,0.86,2024-03-17,NaN,NaN,NaN,NaN
237,FARM0238,South India,44.18,6.90,24.20,222.30,40.59,5.26,Drip,Inorganic,...,SENS0238,2024-03-11,21.783634,82.261681,0.52,2024-03-11,NaN,NaN,NaN,NaN
250,FARM0251,South USA,33.85,6.12,21.46,207.29,42.11,9.62,Drip,Inorganic,...,SENS0251,2024-05-27,26.667370,89.465481,0.44,2024-05-27,Souss-Massa (Agadir),4.313709,22.545315,25.02
263,FARM0264,East Africa,19.19,6.30,23.69,224.47,78.10,6.89,Sprinkler,Inorganic,...,SENS0264,2024-06-09,23.106195,74.846302,0.46,2024-06-09,Haouz (Marrakech),5.561053,22.427162,24.30
290,FARM0291,North India,11.88,6.35,18.58,199.03,69.64,9.02,NaN,Mixed,...,SENS0291,2024-05-22,30.232496,71.570912,0.85,2024-05-22,Gharb (Kenitra),4.719166,23.732710,26.79
297,FARM0298,South USA,23.35,6.59,28.25,168.72,49.41,6.31,Manual,Inorganic,...,SENS0298,2024-05-26,10.392695,84.426785,0.59,2024-05-26,Souss-Massa (Agadir),4.886073,21.794127,27.86
317,FARM0318,Central USA,10.16,5.97,17.35,182.55,44.78,6.17,Sprinkler,Inorganic,...,SENS0318,2024-03-21,29.915324,83.704875,0.88,2024-03-21,Saiss (Fes),3.539955,20.326454,18.78
334,FARM0335,Central USA,15.18,7.21,22.39,143.21,54.23,6.11,NaN,Mixed,...,SENS0335,2024-07-06,17.215850,86.113456,0.88,2024-07-06,Saiss (Fes),6.263023,19.386593,26.49
340,FARM0341,South USA,21.91,7.32,17.05,88.64,51.06,5.13,Drip,Inorganic,...,SENS0341,2024-01-08,21.987956,76.231469,0.52,2024-01-08,Souss-Massa (Agadir),2.016244,15.496736,12.91
350,FARM0351,North India,25.75,7.21,23.85,59.00,48.84,7.96,Manual,Mixed,...,SENS0351,2024-04-07,29.100278,81.377104,0.59,2024-04-07,Gharb (Kenitra),2.992088,16.595179,19.22
387,FARM0388,North India,37.96,7.43,30.12,293.66,79.08,7.66,Drip,Mixed,...,SENS0388,2024-02-27,32.774644,73.140651,0.48,2024-02-27,Gharb (Kenitra),3.039233,21.129885,16.68
388,FARM0389,East Africa,35.64,5.70,27.94,133.65,46.89,9.09,NaN,Inorganic,...,SENS0389,2024-04-04,17.168957,73.425236,0.46,2024-04-04,Haouz (Marrakech),6.219055,23.565569,24.60
462,FARM0463,South USA,20.47,7.13,33.25,89.80,41.08,6.35,NaN,Mixed,...,SENS0463,2024-05-02,28.168865,75.647282,0.85,2024-05-02,Souss-Massa (Agadir),4.782504,22.027763,26.24
480,FARM0481,North India,32.97,6.38,17.80,236.77,40.29,9.30,Sprinkler,Organic,...,SENS0481,2024-02-16,32.524945,73.206250,0.42,2024-02-16,Gharb (Kenitra),2.272698,14.512064,14.05
488,FARM0489,Central USA,32.05,5.73,23.72,170.71,66.19,9.71,Drip,Organic,...,SENS0489,2024-05-16,11.519835,89.449480,0.41,2024-05-16,Saiss (Fes),5.329416,13.551501,27.56

In [17]:
mild_crops['crop_type'].unique()

<StringArray>
['Wheat', 'Maize', 'Soybean', 'Cotton', 'Rice']
Length: 5, dtype: str

In [18]:
cotton_m = mild_crops[mild_crops["crop_type"] == 'Cotton']
cotton_m.drop(columns=['crop_type','crop_disease_status'],inplace=True)
cotton_m

,farm_id,region_x,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,fertilizer_type,...,sensor_id,timestamp,latitude,longitude,NDVI_index,date_join,region_maroc,et0,wind_speed_max,radiation_sum
21,FARM0022,Central USA,12.45,6.83,21.60,128.48,82.40,8.32,Manual,Mixed,...,SENS0022,2024-04-21,13.182195,78.408927,0.86,2024-04-21,Saiss (Fes),3.989644,17.727943,23.20
29,FARM0030,Central USA,18.83,5.66,15.39,184.85,90.00,6.10,Drip,Mixed,...,SENS0030,2024-03-27,13.809559,72.524419,0.70,2024-03-27,Saiss (Fes),3.839160,26.302181,18.21
51,FARM0052,North India,19.61,6.63,28.72,236.17,42.45,7.64,NaN,Inorganic,...,SENS0052,2024-03-08,25.522279,83.555289,0.73,2024-03-08,Gharb (Kenitra),3.142239,24.967499,16.91
110,FARM0111,North India,11.11,6.32,30.38,241.46,88.92,7.88,NaN,Inorganic,...,SENS0111,2024-05-21,19.391138,83.654607,0.70,2024-05-21,Gharb (Kenitra),4.244592,20.005120,23.92
191,FARM0192,Central USA,33.16,6.82,20.40,201.41,46.86,8.98,Drip,Mixed,...,SENS0192,2024-03-13,14.966167,73.994988,0.46,2024-03-13,Saiss (Fes),2.524087,19.523155,14.82
206,FARM0207,North India,23.56,7.41,34.52,128.16,67.61,4.08,Manual,Organic,...,SENS0207,2024-05-27,27.738636,77.354822,0.65,2024-05-27,Gharb (Kenitra),4.620668,16.873980,26.47
219,FARM0220,Central USA,17.82,7.04,29.66,122.75,63.24,7.06,NaN,Inorganic,...,SENS0220,2024-04-19,28.930152,72.807414,0.40,2024-04-19,Saiss (Fes),4.758348,16.299694,20.51
253,FARM0254,East Africa,16.64,5.87,21.95,233.10,53.77,8.99,Sprinkler,Organic,...,SENS0254,2024-05-13,21.351974,85.518358,0.60,2024-05-13,Haouz (Marrakech),6.422313,20.160000,27.52
257,FARM0258,East Africa,16.63,6.55,19.98,206.33,48.94,8.50,NaN,Mixed,...,SENS0258,2024-06-16,26.631059,87.656480,0.40,2024-06-16,Haouz (Marrakech),6.982360,20.160000,29.28
259,FARM0260,Central USA,25.66,6.29,29.53,295.74,69.79,7.11,Manual,Organic,...,SENS0260,2024-03-17,32.977802,80.225430,0.64,2024-03-17,Saiss (Fes),4.209635,9.565437,20.64
272,FARM0273,North India,14.69,7.19,24.38,212.39,49.20,6.32,NaN,Organic,...,SENS0273,2024-01-03,33.135877,89.003961,0.43,2024-01-03,Gharb (Kenitra),2.223267,10.630672,11.70
277,FARM0278,East Africa,11.54,5.84,21.70,267.83,83.13,4.97,Sprinkler,Organic,...,SENS0278,2024-04-21,34.024153,75.775611,0.41,2024-04-21,Haouz (Marrakech),5.288523,23.358425,23.84
294,FARM0295,East Africa,14.00,6.69,21.51,74.41,62.26,5.85,NaN,Organic,...,SENS0295,2024-07-02,18.185206,82.899782,0.34,2024-07-02,Haouz (Marrakech),7.069309,19.134262,28.82
324,FARM0325,South USA,37.01,7.25,23.11,247.46,58.52,6.79,Drip,Mixed,...,SENS0325,2024-05-04,28.822200,83.961100,0.67,2024-05-04,Souss-Massa (Agadir),4.480242,20.491560,27.64
332,FARM0333,Central USA,41.36,7.44,30.08,298.52,73.34,8.80,NaN,Inorganic,...,SENS0333,2024-08-04,12.921902,70.495912,0.67,2024-08-04,Saiss (Fes),7.223443,16.992609,26.77
364,FARM0365,Central USA,31.07,7.13,29.76,163.32,41.37,4.31,Sprinkler,Mixed,...,SENS0365,2024-05-24,17.638688,81.516187,0.37,2024-05-24,Saiss (Fes),5.970071,17.429354,27.27
367,FARM0368,South USA,14.15,6.93,18.81,265.48,79.11,5.73,NaN,Inorganic,...,SENS0368,2024-02-25,28.167702,73.787263,0.41,2024-02-25,Souss-Massa (Agadir),3.531454,18.356470,19.07
372,FARM0373,North India,22.48,6.92,24.70,173.25,82.29,9.20,Drip,Inorganic,...,SENS0373,2024-06-15,30.564294,81.264948,0.70,2024-06-15,Gharb (Kenitra),4.871033,18.532135,27.42
409,FARM0410,South India,43.86,5.57,24.86,226.01,70.30,4.04,NaN,Organic,...,SENS0410,2024-04-10,26.495961,81.314141,0.71,2024-04-10,NaN,NaN,NaN,NaN
435,FARM0436,Central USA,39.95,6.29,15.21,78.67,85.86,5.96,NaN,Inorganic,...,SENS0436,2024-05-09,13.506394,86.408534,0.80,2024-05-09,Saiss (Fes),6.584205,10.365251,26.29
445,FARM0446,South USA,39.89,7.02,33.43,198.80,47.64,8.36,Manual,Inorganic,...,SENS0446,2024-04-11,11.798491,72.733127,0.58,2024-04-11,Souss-Massa (Agadir),7.958767,22.127556,26.06
469,FARM0470,East Africa,14.89,6.48,21.26,277.70,89.84,7.64,Sprinkler,Mixed,...,SENS0470,2024-02-15,31.402129,74.304259,0.38,2024-02-15,Haouz (Marrakech),3.534733,15.893093,15.40
493,FARM0494,South India,18.11,6.95,22.37,275.54,44.68,5.09,Sprinkler,Organic,...,SENS0494,2024-02-26,17.754006,87.705061,0.79,2024-02-26,NaN,NaN,NaN,NaN
497,FARM0498,North India,15.93,5.72,17.03,288.96,57.87,7.69,Drip,Inorganic,...,SENS0498,2024-04-20,23.262016,81.992230,0.71,2024-04-20,Gharb (Kenitra),3.457850,13.276144,19.39

In [19]:
cotton_m.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,22.000000,22.000000,22.000000
mean,23.100000,6.618333,24.180833,209.449583,65.807917,6.892083,25.364583,120.541667,4027.146667,23.007499,79.952619,0.587917,4.860270,18.098752,22.779545
std,10.643732,0.564767,5.454837,66.447771,16.600001,1.631684,13.494257,18.579978,1273.034728,7.399916,5.577502,0.160867,1.619281,4.378786,5.129957
min,11.110000,5.570000,15.210000,74.410000,41.370000,4.040000,6.810000,90.000000,2130.860000,11.798491,70.495912,0.340000,2.223267,9.565437,11.700000
25%,14.840000,6.290000,21.045000,170.767500,49.135000,5.820000,11.992500,103.750000,2914.950000,16.970558,74.226941,0.410000,3.610840,16.443265,19.150000
50%,18.470000,6.755000,22.740000,219.200000,65.425000,7.085000,25.810000,118.500000,3925.610000,24.392148,81.289545,0.645000,4.550455,18.444302,23.880000
75%,31.592500,7.025000,29.562500,266.067500,82.317500,8.330000,36.342500,141.250000,5098.787500,28.849188,83.731230,0.702500,6.309252,20.160000,27.145000
max,43.860000,7.440000,34.520000,298.520000,90.000000,9.200000,49.680000,147.000000,5980.830000,34.024153,89.003961,0.860000,7.958767,26.302181,29.280000

In [20]:
cotton_s.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,28.000000,28.000000,28.000000
mean,26.395625,6.568125,24.701563,181.759687,60.046250,7.548437,27.021562,116.625000,3967.243125,23.749854,79.577517,0.615313,4.490942,19.899749,21.378929
std,9.332604,0.556512,6.396262,66.688167,15.670886,1.675755,11.752007,15.718799,1349.624671,7.640920,6.025700,0.184670,1.548598,4.974547,5.918162
min,10.160000,5.700000,15.110000,52.360000,40.290000,4.380000,6.890000,94.000000,2046.410000,10.392695,70.726797,0.340000,1.637935,9.957108,3.580000
25%,19.027500,6.110000,18.985000,132.720000,45.927500,6.282500,17.100000,106.500000,2511.757500,17.204127,74.693028,0.455000,3.307538,15.781765,17.700000
50%,26.460000,6.565000,23.785000,190.790000,55.945000,7.865000,26.010000,115.000000,4125.870000,23.412194,79.342136,0.590000,4.654073,20.088987,24.345000
75%,33.190000,7.070000,30.567500,237.012500,75.970000,9.037500,38.580000,125.000000,5048.022500,30.565850,84.360466,0.805000,5.641217,22.456700,25.760000
max,44.180000,7.470000,34.440000,295.180000,85.980000,9.820000,49.880000,145.000000,5970.390000,33.365547,89.672164,0.900000,7.539997,31.404713,27.860000

In [21]:
df.head()

,farm_id,region_x,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,timestamp,latitude,longitude,NDVI_index,crop_disease_status,date_join,region_maroc,et0,wind_speed_max,radiation_sum
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,2024-03-19,14.970941,82.997689,0.63,Mild,2024-03-19,Gharb (Kenitra),4.238751,15.629972,21.21
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,2024-04-21,16.613022,70.869009,0.58,NaN,2024-04-21,Souss-Massa (Agadir),4.825523,40.464382,26.15
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,2024-02-28,19.503156,79.068206,0.80,Mild,2024-02-28,Souss-Massa (Agadir),3.696556,18.864824,19.71
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,2024-05-14,31.071298,85.519998,0.44,NaN,2024-05-14,Saiss (Fes),4.771625,19.800000,23.20
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,2024-04-13,16.568540,81.691720,0.84,Severe,2024-04-13,Saiss (Fes),6.550368,31.079075,25.68

In [22]:
df.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,409.000000,409.000000,409.000000
mean,26.750140,6.523980,24.675740,181.685740,65.194460,7.03014,26.586980,119.496000,4032.92694,22.442473,80.392248,0.602060,4.503720,20.401949,21.207262
std,10.150053,0.585558,5.348899,72.293091,14.642849,1.69167,13.202429,16.798046,1174.43304,7.283492,5.910664,0.175402,1.647743,7.539521,5.949149
min,10.160000,5.510000,15.000000,50.170000,40.230000,4.01000,5.050000,90.000000,2023.56000,10.004243,70.020021,0.300000,1.070605,7.993297,1.140000
25%,17.890000,6.030000,20.295000,119.217500,51.865000,5.66750,14.945000,105.750000,2994.82000,16.263202,75.374713,0.447500,3.349063,15.391840,17.000000
50%,25.855000,6.530000,24.655000,191.545000,65.685000,6.99500,25.980000,119.000000,4071.69000,21.981743,80.650284,0.610000,4.260496,19.272614,22.300000
75%,36.022500,7.040000,29.090000,239.035000,77.995000,8.47000,38.005000,134.000000,5062.11000,28.528948,85.654629,0.750000,5.718628,24.130743,26.620000
max,44.980000,7.500000,34.840000,298.960000,90.000000,10.00000,49.940000,150.000000,5998.29000,34.981531,89.991901,0.900000,10.369526,50.432130,29.620000

In [26]:
df['crop_disease_status'] = df['crop_disease_status'].fillna("unknown")

In [28]:
df['crop_disease_status'].unique()

<StringArray>
['Mild', 'unknown', 'Severe', 'Moderate']
Length: 4, dtype: str

In [29]:
unknown = df[df['crop_disease_status'] == 'unknown']
unknown.describe()

,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,pesticide_usage_ml,total_days,yield_kg_per_hectare,latitude,longitude,NDVI_index,et0,wind_speed_max,radiation_sum
count,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000,104.000000,104.000000,104.000000
mean,26.618769,6.517231,24.723846,177.430846,65.281231,6.995231,26.433846,121.523077,4082.647615,22.176578,80.597100,0.601846,4.457298,19.554901,20.895481
std,10.002995,0.589458,5.086874,70.260362,15.203665,1.758214,13.299074,16.421396,1129.666219,7.520990,6.180785,0.173361,1.555712,7.474591,5.584171
min,10.220000,5.530000,15.250000,52.420000,40.420000,4.020000,5.360000,90.000000,2029.160000,10.102747,70.117979,0.300000,1.220299,9.064569,3.580000
25%,17.797500,5.992500,20.520000,116.470000,51.145000,5.545000,15.070000,108.250000,3163.210000,15.648837,75.160581,0.442500,3.463365,14.058450,16.957500
50%,25.170000,6.485000,24.850000,186.750000,68.125000,6.885000,25.305000,120.000000,4036.935000,22.206354,80.744147,0.620000,4.219847,17.771707,22.170000
75%,35.937500,7.040000,28.715000,235.602500,77.660000,8.572500,37.790000,136.000000,5203.502500,28.206037,86.216380,0.750000,5.501050,23.731403,26.075000
max,44.910000,7.490000,33.950000,298.090000,88.820000,9.980000,49.940000,150.000000,5954.030000,34.806428,89.801528,0.900000,9.401630,42.522690,29.260000

,farm_id,region_x,crop_type,irrigation_type,fertilizer_type,sowing_date,harvest_date,sensor_id,timestamp,crop_disease_status,date_join,region_maroc
count,130,130,130,95,130,130,130,130,130,130,130,104
unique,130,5,5,3,3,67,78,130,96,1,96,4
top,FARM0002,Central USA,Maize,Sprinkler,Organic,2024-02-14,2024-07-04,SENS0002,2024-04-14,unknown,2024-04-14,Saiss (Fes)
freq,1,30,36,32,50,6,5,1,4,130,4,30