In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Dataset/uv_data.csv')
df.head()

,Month,Day,Hour,Solar_Radiation,Cloud_Cover,Ozone_Level,Altitude,UV_Index,UV_Risk_Level
0,7,16,16,759.764166,0.875883,364.894304,0.241742,0.587353,Low
1,4,4,20,654.386905,0.539095,229.287251,0.441490,1.203476,Low
2,11,11,7,269.222261,0.282472,366.585943,0.893932,1.285757,Low
3,8,24,14,419.846112,0.425228,308.059306,0.269279,1.272356,Low
4,5,23,13,805.412606,0.037571,368.933182,2.732479,6.068712,High

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Month            1000 non-null   int64
 1   Day              1000 non-null   int64
 2   Hour             1000 non-null   int64
 3   Solar_Radiation  1000 non-null   float64
 4   Cloud_Cover      1000 non-null   float64
 5   Ozone_Level      1000 non-null   float64
 6   Altitude         1000 non-null   float64
 7   UV_Index         1000 non-null   float64
 8   UV_Risk_Level    1000 non-null   str
dtypes: float64(5), int64(3), str(1)
memory usage: 70.4 KB

In [4]:
df.describe()

,Month,Day,Hour,Solar_Radiation,Cloud_Cover,Ozone_Level,Altitude,UV_Index
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,6.454000,14.314000,11.426000,547.958736,0.497176,297.613685,1.502595,1.572915
std,3.525665,8.170689,6.924773,260.145029,0.285633,57.635504,0.863333,1.321936
min,1.000000,1.000000,0.000000,100.121224,0.000012,200.006144,0.002830,0.001036
25%,3.000000,7.000000,5.000000,333.832762,0.249504,247.468695,0.772781,0.556376
50%,6.000000,14.000000,11.000000,545.803120,0.500236,296.652636,1.468251,1.222073
75%,10.000000,22.000000,17.000000,778.205276,0.738917,346.338115,2.225567,2.326334
max,12.000000,28.000000,23.000000,998.512760,0.999558,399.549878,2.998051,7.157764

In [5]:
df.describe(include='str')

       UV_Risk_Level
count           1000
unique             4
top              Low
freq             846

In [6]:
df['UV_Risk_Level'].unique()

<StringArray>
['Low', 'High', 'Moderate', 'Extreme']
Length: 4, dtype: str