In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Dataset/dataset_final.csv")

In [3]:
df.head()

,farm_id,region_x,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,timestamp,latitude,longitude,NDVI_index,crop_disease_status,date_join,region_maroc,et0,wind_speed_max,radiation_sum
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,2024-03-19,14.970941,82.997689,0.63,Mild,2024-03-19,Gharb (Kenitra),4.238751,15.629972,21.21
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,2024-04-21,16.613022,70.869009,0.58,NaN,2024-04-21,Souss-Massa (Agadir),4.825523,40.464382,26.15
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,2024-02-28,19.503156,79.068206,0.80,Mild,2024-02-28,Souss-Massa (Agadir),3.696556,18.864824,19.71
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,2024-05-14,31.071298,85.519998,0.44,NaN,2024-05-14,Saiss (Fes),4.771625,19.800000,23.20
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,2024-04-13,16.568540,81.691720,0.84,Severe,2024-04-13,Saiss (Fes),6.550368,31.079075,25.68

In [45]:
data = {
    "Roll No":[12,34,56,76],
    "Name" : ['Aromal','Aromal','Nether','Hell'],
    "Gender" : ['M','M','M','F'],
    "Salary" : [25000,25000,28000,300000],
    "Age" : [23,23,27,45],
    "Experience" : [1,1,2,13]}
df = pd.DataFrame(data)

### unique

In [9]:
test_df['Name'].unique()

<StringArray>
['Aromal', 'Nether', 'Hell']
Length: 3, dtype: str

In [10]:
test_df['Name'].nunique()

3

### value_counts

In [11]:
test_df['Name'].value_counts()

Name
Aromal    2
Nether    1
Hell      1
Name: count, dtype: int64

In [13]:
test_df['Name'].value_counts(normalize=True)*100
# normalize compresses or expands the frequency of each values to a scale from 0 to 1

Name
Aromal    50.0
Nether    25.0
Hell      25.0
Name: proportion, dtype: float64

## Statistical Values

In [ ]:
df['col_name'].mean()
df['col_name'].median()
df['col_name'].mode()
df['col_name'].min()
df['col_name'].max()
df['col_name'].std()
df['col_name'].var()
df['col_name'].count()
# Quantile is the part of the 100% 
# in case of .25 that is 25 % of he total 100%
# .50 is 50 percentile also known as median
df['col_name'].quantile(0.25) 
df['col_name'].quantile(0.50)
df['col_name'].quantile(0.75)

### groupby

In [ ]:
df.groupby('Department')['Salary'].mean()

In [ ]:
df.groupby('Department')['Salary'].agg(
    ['count','max','min',]
)

In [ ]:
df.groupby('Department')['Salary'].agg(
    {
     'Salary' : ['count','max','min'],
    'Name':['value_count','mode']
    }
)

In [ ]:
df.groupby('Department')['Salary'].agg(
    Average_sal=('Salary','mean')
)

In [ ]:
df['Annual_Salary'] = df['monthly'] * 12

### Lambda/Where

In [ ]:
df['Status'] = df['Salary'].apply(
    lambda x : 'High' if x > 50000 else 'Low'
)

In [ ]:
df['Status'] = np.where(
    df['Salary'] > 50000,
    'High',
    'Low'
)

In [21]:
df['Gender'].replace(
    {
        "M": 'Male',
        'F': 'Female'
    },inplace = True)

C:\Users\aroma\AppData\Local\Temp\ipykernel_20276\4033284706.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Gender'].replace(

0      Male
1      Male
2      Male
3    Female
Name: Gender, dtype: str

In [ ]:
df.replace({
    'Kochi' : 'Cochin',
    'Trivandrum' : 'Thiruvananthapuram'
})

### Outlier Detection

In [30]:
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3-Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]
cleaned = df[(df['Salary'] >= lower) & (df['Salary'] <= upper)]

### Correlation

In [ ]:
df.corr(numeric_only=True)

In [33]:
df[['Age','Experience','Salary']].corr()

                 Age  Experience    Salary
Age         1.000000    0.995019  0.985556
Experience  0.995019    1.000000  0.997529
Salary      0.985556    0.997529  1.000000

### Crosstab

In [ ]:
pd.crosstab(df['Gender'],df['Results'])
## first param becomes the kabel
## Second param becomes the column name

In [ ]:
result = df.pivot(
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc = "mean"
)

print(result)

### Join

In [ ]:
pd.merge(df1,df2,on = 'Employee_ID',how='inner')
pd.merge(df1,df2,on = 'Employee_ID',how='left')
pd.merge(df1,df2,on = 'Employee_ID',how='right')
pd.merge(df1,df2,on = 'Employee_ID',how='outer')

### concatenate

In [ ]:
pd.concat([df1,df2])

### Adding/Removing Coloumns

In [42]:
df.drop('Salary',axis = 1) ## coloumn name incase of axis 1

   Roll No    Name Gender  Salary  Age  Experience
0       12  Aromal      M   25000   23           1
1       34  Aromal      M   25000   23           1
2       56  Nether      M   28000   27           2
3       76    Hell      F  300000   45          13

In [44]:
df.drop(1,axis = 0)  ## label/row index incase of axis 0

   Roll No    Name Gender  Salary  Age  Experience
0       12  Aromal      M   25000   23           1
2       56  Nether      M   28000   27           2
3       76    Hell      F  300000   45          13

### Reset index

In [ ]:
df.reset_index(drop=True,inplace=True)
df.set_index('Employee_ID')

### Date Analysis

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = df['Date'].dt.year
df['Date'] = df['Date'].dt.month
df['Date'] = df['Date'].dt.month_name()
df['Date'] = df['Date'].dt.day
df['Date'] = df['Date'].dt.day_name()
df['Date'] = df['Date'].dt.

### Export Data

In [ ]:
df.to_csv('filename.csv',index = 'False')
df.to_excel('filename.xlsx',index = 'False')
df.to_json('filename.json')